[variables]
main_domain = "${domain}"

[config]
env = [
  "KUMA_USERNAME=",
  "KUMA_PASSWORD=",
  "SMTP_HOST=",
  "SMTP_PORT=",
  "SMTP_USERNAME=",
  "SMTP_PASSWORD=",
  "SMTP_FROM_NAME=",
  "SMTP_FROM_ADDRESS=",
  "SMTP_TO_ADDRESS="
]

[[config.domains]]
serviceName = "uptime-kuma"
port        = 3001
host        = "${main_domain}"
path        = "/"
